
BLACK_COLOR = "BLACK"
WHITE_COLOR = "WHITE"
EMPTY_STRING = ""
EMPTY_FIELD = '.'

#PIECES
BLACK_KING = 'k'
BLACK_QUEEN = 'q'
BLACK_BISHOP = 'b'
BLACK_KNIGHT = 'n'
BLACK_ROOK = 'r'
BLACK_PAWN = 'p'
WHITE_KING = 'K'
WHITE_QUEEN = 'Q'
WHITE_BISHOP = 'B'
WHITE_KNIGHT = 'N'
WHITE_ROOK = 'R'
WHITE_PAWN = 'P'

KING = [BLACK_KING, WHITE_KING]
QUEEN = [BLACK_QUEEN, WHITE_QUEEN]
BISHOP = [BLACK_BISHOP, WHITE_BISHOP]
KNIGHT = [BLACK_KNIGHT, WHITE_KNIGHT]
ROOK = [BLACK_ROOK, WHITE_ROOK]
PAWN = [BLACK_PAWN, WHITE_PAWN]

BLACK_PIECES = [BLACK_KING, BLACK_QUEEN, BLACK_BISHOP, BLACK_KNIGHT, BLACK_ROOK, BLACK_PAWN]
WHITE_PIECES = [WHITE_KING, WHITE_QUEEN, WHITE_BISHOP, WHITE_KNIGHT, WHITE_ROOK, WHITE_PAWN]

BLANK_ROW = [EMPTY_FIELD] * 8
FIRST_ROW_BLACK = [BLACK_ROOK, BLACK_KNIGHT, BLACK_BISHOP, BLACK_QUEEN, BLACK_KING, BLACK_BISHOP, BLACK_KNIGHT, BLACK_ROOK]
FIRST_ROW_WHITE = [WHITE_ROOK, WHITE_KNIGHT, WHITE_BISHOP, WHITE_QUEEN, WHITE_KING, WHITE_BISHOP, WHITE_KNIGHT, WHITE_ROOK]
SECOND_ROW_BLACK = [BLACK_PAWN] * 8
SECOND_ROW_WHITE = [WHITE_PAWN] * 8

PLAYER_BLACK_INITIAL_BOARD = [FIRST_ROW_WHITE, SECOND_ROW_WHITE, BLANK_ROW, BLANK_ROW,
                              BLANK_ROW, BLANK_ROW, SECOND_ROW_BLACK, FIRST_ROW_BLACK]
PLAYER_WHITE_INITIAL_BOARD = [FIRST_ROW_BLACK, SECOND_ROW_BLACK, BLANK_ROW, BLANK_ROW,
                              BLANK_ROW, BLANK_ROW, SECOND_ROW_WHITE, FIRST_ROW_WHITE]
